# Generated by Django 3.2.8 on 2021-11-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='itemtype',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegitables', 'Vegitables'), ('spices', 'Spices'), ('others', 'Others')], default='fruits', max_length=20),
        ),
    ]
